sro_prover:
  M: 8
  L: 24
  B: 64
  tau1: 0.75
  tau2: 0.80
  delta: 0.10
  kappa: 0.80   # tuned on data/processed/dev_pairs.csv, coverage ≈ 97.7%
  epsilon: 0.02
  max_sentences_per_claim: 64
paths:
  artifacts_dir: artifacts
  proofs_dir: artifacts/proofs
  logs_dir: artifacts/logs
retrieval:
  corpus_jsonl: data/corpus/corpus.jsonl
  k_bm25: 200
  k_dense: 200
  k_fused: 24
  mmr_lambda: 0.7
  rrf_c: 60
  use_cross_encoder: true
  rerank_top: 64
claims:
  K: 3
  min_question_cosine: 0.30
  hedge_terms:
    - "\\brumor(s|ed)?\\b"
    - "\\breportedly\\b"
    - "\\bmay\\b"
    - "\\bmight\\b"
    - "\\bpossibly\\b"
    - "\\bsuggest(ed|s|ing)?\\b"
    - "\\baccording to (sources|rumors)\\b"
  reliability_weights:
    news: 1.0
    press: 0.95
    blog: 0.60
    seed: 0.80
    alt: 0.75

